In [1]:
import pandas as pd

In [2]:
df = pd.read_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Match Dataset with Market Values (5).xlsx", index_col=0)

In [3]:
df.reset_index(drop=True, inplace=True)

In [4]:
wage_df = pd.read_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\WAGE DATA.xlsx", index_col=0)

In [5]:
wage_df

              Squad  Weekly Wages  Season
0   Manchester City       4205000    2024
1           Chelsea       3667500    2024
2    Manchester Utd       3341346    2024
3           Arsenal       3163000    2024
4         Liverpool       2415000    2024
..              ...           ...     ...
15      Bournemouth        828096    2017
16    Newcastle Utd        811904    2017
17         Brighton        767481    2017
18          Burnley        626096    2017
19     Huddersfield        492442    2017

[160 rows x 3 columns]

In [6]:
def add_wages(df, wages_df):    
    for team, wages, season in wages_df.values:
        #df = df.loc[df['season_x'] == season]
        df.loc[(df['home_team'] == team) & (df['season_x'] == season), 'home_team_wages'] = wages
        df.loc[(df['away_team'] == team) & (df['season_x'] == season), 'away_team_wages'] = wages
    return df

In [7]:
df = add_wages(df, wage_df)

In [8]:
df

,date,comp_x,season_x,round_x,home_team,away_team,home points,away points,home constant points,away constant points,...,home_team_home GF_rolling_10,home_team_home GA_rolling_10,home_team_home xG_rolling_10,home_team_home xGA_rolling_10,home_team_home adjusted GS_rolling_10,home_team_home adjusted GC_rolling_10,home_team_market_value,away_team_market_value,home_team_wages,away_team_wages
0,2018-08-03,Championship,2018,Matchweek 1,Reading,Derby County,0.0,0.9,1.0,1.0,...,0.34,2.82,NaN,NaN,NaN,NaN,66250000.0,9.430000e+07,NaN,NaN
1,2018-08-04,Championship,2018,Matchweek 1,Birmingham City,Norwich City,0.3,0.3,1.0,1.0,...,0.54,2.12,NaN,NaN,NaN,NaN,42500000.0,8.630000e+07,NaN,NaN
2,2018-08-04,Championship,2018,Matchweek 1,Brentford,Rotherham Utd,0.9,0.0,1.0,1.0,...,0.74,1.92,NaN,NaN,NaN,NaN,76350000.0,1.158000e+07,NaN,NaN
3,2018-08-04,Championship,2018,Matchweek 1,Bristol City,Nott'ham Forest,0.3,0.3,1.0,1.0,...,1.34,2.52,NaN,NaN,NaN,NaN,72550000.0,8.310000e+07,NaN,NaN
4,2018-08-04,Championship,2018,Matchweek 1,Ipswich Town,Blackburn,0.3,0.3,1.0,1.0,...,-0.16,2.32,NaN,NaN,NaN,NaN,26850000.0,3.475000e+07,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5967,2025-05-06,Premier League,2024,Matchweek 38,Newcastle Utd,Everton,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,659650000.0,3.238000e+08,1900000.0,1183500.0
5968,2025-05-06,Premier League,2024,Matchweek 38,Nott'ham Forest,Chelsea,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,376900000.0,1.110000e+09,1203462.0,3667500.0
5969,2025-05-06,Premier League,2024,Matchweek 38,Southampton,Arsenal,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,268800000.0,1.170000e+09,633500.0,3163000.0
5970,2025-05-06,Premier League,2024,Matchweek 38,Tottenham,Brighton,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,801700000.0,5.581000e+08,2150500.0,1076577.0
5971,2025-05-06,Premier League,2024,Matchweek 38,Wolves,Brentford,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,361100000.0,4.327300e+08,1045885.0,797500.0

In [9]:
df.columns

Index(['date', 'comp_x', 'season_x', 'round_x', 'home_team', 'away_team',
       'home points', 'away points', 'home constant points',
       'away constant points', 'home GF', 'away GF', 'home adjusted GS',
       'away adjusted GS', 'home GA', 'away GA', 'home adjusted GC',
       'away adjusted GC', 'home xG', 'away xG', 'home xGA', 'away xGA',
       'home GD', 'away GD', 'home adjusted GD', 'away adjusted GD',
       'home constant GD', 'away constant GD', 'home form last 5',
       'away form last 5', 'home GD form last 5', 'away GD form last 5',
       'home constant GD form last 5', 'away constant GD form last 5',
       'home xGD', 'away xGD', 'home constant xGD', 'away constant xGD',
       'home xGD form last 5', 'away xGD form last 5',
       'home constant xGD form last 5', 'away constant xGD form last 5',
       'home points form last 5', 'away points form last 5',
       'home constant points form last 5', 'away constant points form last 5',
       'home avg pos', 'away avg pos', 'home previous position',
       'away previous position', 'home previous expected position',
       'away previous expected position', 'home previous points',
       'away previous points', 'home previous GD', 'away previous GD',
       'home previous xGD', 'away previous xGD',
       'away_team_away points_rolling_10',
       'away_team_away constant points_rolling_10',
       'away_team_away GF_rolling_10', 'away_team_away GA_rolling_10',
       'away_team_away xG_rolling_10', 'away_team_away xGA_rolling_10',
       'away_team_away adjusted GS_rolling_10',
       'away_team_away adjusted GC_rolling_10',
       'home_team_home points_rolling_10',
       'home_team_home constant points_rolling_10',
       'home_team_home GF_rolling_10', 'home_team_home GA_rolling_10',
       'home_team_home xG_rolling_10', 'home_team_home xGA_rolling_10',
       'home_team_home adjusted GS_rolling_10',
       'home_team_home adjusted GC_rolling_10', 'home_team_market_value',
       'away_team_market_value', 'home_team_wages', 'away_team_wages'],
      dtype='object')

In [10]:
df.rename(columns={'comp_x':'comp','season_x':'season','round_x':'round'}, inplace=True)

In [11]:
#df.drop(['home points', 'away points', 'home GD', 'away GD','home xGD', 'away xGD'], axis=1, inplace=True)
df.drop(['home GD', 'away GD','home constant GD', 'away constant GD','home xGD', 'away xGD', 'home constant xGD', 'away constant xGD','home constant points',
       'away constant points'], axis=1, inplace=True)

In [12]:
df.columns

Index(['date', 'comp', 'season', 'round', 'home_team', 'away_team',
       'home points', 'away points', 'home GF', 'away GF', 'home adjusted GS',
       'away adjusted GS', 'home GA', 'away GA', 'home adjusted GC',
       'away adjusted GC', 'home xG', 'away xG', 'home xGA', 'away xGA',
       'home adjusted GD', 'away adjusted GD', 'home form last 5',
       'away form last 5', 'home GD form last 5', 'away GD form last 5',
       'home constant GD form last 5', 'away constant GD form last 5',
       'home xGD form last 5', 'away xGD form last 5',
       'home constant xGD form last 5', 'away constant xGD form last 5',
       'home points form last 5', 'away points form last 5',
       'home constant points form last 5', 'away constant points form last 5',
       'home avg pos', 'away avg pos', 'home previous position',
       'away previous position', 'home previous expected position',
       'away previous expected position', 'home previous points',
       'away previous points', 'home previous GD', 'away previous GD',
       'home previous xGD', 'away previous xGD',
       'away_team_away points_rolling_10',
       'away_team_away constant points_rolling_10',
       'away_team_away GF_rolling_10', 'away_team_away GA_rolling_10',
       'away_team_away xG_rolling_10', 'away_team_away xGA_rolling_10',
       'away_team_away adjusted GS_rolling_10',
       'away_team_away adjusted GC_rolling_10',
       'home_team_home points_rolling_10',
       'home_team_home constant points_rolling_10',
       'home_team_home GF_rolling_10', 'home_team_home GA_rolling_10',
       'home_team_home xG_rolling_10', 'home_team_home xGA_rolling_10',
       'home_team_home adjusted GS_rolling_10',
       'home_team_home adjusted GC_rolling_10', 'home_team_market_value',
       'away_team_market_value', 'home_team_wages', 'away_team_wages'],
      dtype='object')

In [13]:
df.rename(columns={
       'home_team':'HT', 
       'away_team':'AT',
       'home GD form last 5': 'HT GD form 5', 
       'away GD form last 5': 'AT GD form 5', 
       'home adjusted GS' : 'HT GS',
       'away adjusted GS' : 'AT GS',
       'home adjusted GC' : 'HT GC',
       'away adjusted GC' : 'AT GC',
       'home adjusted GD' : 'HT AdjGD',
       'away adjusted GD' : 'AT AdjGD',
       'home form last 5' : 'HT AdjGD form 5',
       'away form last 5' : 'AT AdjGD form 5',
       'home_team_home adjusted GS_rolling_10' : 'HT Home GS form 10',
       'home_team_home adjusted GC_rolling_10' : 'HT Home GC form 10',
       'away_team_away adjusted GS_rolling_10' : 'AT Away GS form 10',
       'away_team_away adjusted GC_rolling_10' : 'AT Away GC form 10',
       'home constant GD form last 5': 'HT constant GD form 5',
       'away constant GD form last 5': 'AT constant GD form 5',
       'home GD form last 10': 'HT GD form 10',
       'away GD form last 10': 'AT GD form 10', 
       'home GD form last 20': 'HT GD form 20', 
       'away GD form last 20': 'AT GD form 20',
       'home xGD form last 5': 'HT xGD form 5', 
       'away xGD form last 5': 'AT xGD form 5',
       'home constant xGD form last 5': 'HT constant xGD form 5',
       'away constant xGD form last 5': 'AT constant xGD form 5', 
       'home xGD form last 10': 'HT xGD form 10',
       'away xGD form last 10': 'AT xGD form 10', 
       'home xGD form last 20': 'HT xGD form 20',
       'away xGD form last 20': 'AT xGD form 20', 
       'home points form last 5': 'HT points form 5',
       'away points form last 5': 'AT points form 5',
       'home constant points form last 5': 'HT constant points form 5',
       'away constant points form last 5': 'AT constant points form 5',
       'home points form last 10': 'HT points form 10',
       'away points form last 10': 'AT points form 10',
       'home points form last 20': 'HT points form 20',
       'away points form last 20': 'AT points form 20', 
       'home avg pos': 'HT avg pos', 
       'away avg pos': 'AT avg pos',
       'home previous position': 'HT prev pos', 
       'away previous position': 'AT prev pos',
       'home previous expected position': 'HT prev exp pos', 
       'away previous expected position': 'AT prev exp pos',
       'home previous points': 'HT prev points',
       'away previous points': 'AT prev points',
       'home previous xGD': 'HT prev xGD',
       'away previous xGD': 'AT prev xGD',
       'home previous GD': 'HT prev GD',
       'away previous GD': 'AT prev GD',
       'away_team_away points_rolling_10': 'AT Away points form 10',
       'away_team_away constant points_rolling_10': 'AT Away constant points form 10', 
       'away_team_away GD_rolling_10': 'AT Away GD form 10',
       'away_team_away xGD_rolling_10': 'AT Away xGD form 10', 
       'home_team_home points_rolling_10': 'HT Home points form 10',
       'home_team_home constant points_rolling_10': 'HT Home constant points form 10',
       'home_team_home GD_rolling_10': 'HT Home GD form 10', 
       'home_team_home xGD_rolling_10': 'HT Home xGD form 10',
       'home_team_market_value':'HT Market Value', 
       'away_team_market_value':'AT Market Value',
       'away_team_away GF_rolling_10': 'AT Away GF form 10',
       'away_team_away GA_rolling_10': 'AT Away GA form 10',
       'away_team_away xG_rolling_10': 'AT Away xG form 10',
       'away_team_away xGA_rolling_10': 'AT Away xGA form 10',
       'home_team_home GF_rolling_10': 'HT Home GF form 10', 
       'home_team_home GA_rolling_10': 'HT Home GA form 10',
       'home_team_home xG_rolling_10': 'HT Home xG form 10', 
       'home_team_home xGA_rolling_10': 'HT Home xGA form 10',
       'home_team_wages':'HT Wages',
       'away_team_wages':'AT Wages',
       }, inplace=True)

In [14]:
df.columns

Index(['date', 'comp', 'season', 'round', 'HT', 'AT', 'home points',
       'away points', 'home GF', 'away GF', 'HT GS', 'AT GS', 'home GA',
       'away GA', 'HT GC', 'AT GC', 'home xG', 'away xG', 'home xGA',
       'away xGA', 'HT AdjGD', 'AT AdjGD', 'HT AdjGD form 5',
       'AT AdjGD form 5', 'HT GD form 5', 'AT GD form 5',
       'HT constant GD form 5', 'AT constant GD form 5', 'HT xGD form 5',
       'AT xGD form 5', 'HT constant xGD form 5', 'AT constant xGD form 5',
       'HT points form 5', 'AT points form 5', 'HT constant points form 5',
       'AT constant points form 5', 'HT avg pos', 'AT avg pos', 'HT prev pos',
       'AT prev pos', 'HT prev exp pos', 'AT prev exp pos', 'HT prev points',
       'AT prev points', 'HT prev GD', 'AT prev GD', 'HT prev xGD',
       'AT prev xGD', 'AT Away points form 10',
       'AT Away constant points form 10', 'AT Away GF form 10',
       'AT Away GA form 10', 'AT Away xG form 10', 'AT Away xGA form 10',
       'AT Away GS form 10', 'AT Away GC form 10', 'HT Home points form 10',
       'HT Home constant points form 10', 'HT Home GF form 10',
       'HT Home GA form 10', 'HT Home xG form 10', 'HT Home xGA form 10',
       'HT Home GS form 10', 'HT Home GC form 10', 'HT Market Value',
       'AT Market Value', 'HT Wages', 'AT Wages'],
      dtype='object')

In [15]:
pd.set_option('display.max_columns', None)  
df[df['HT'] == 'Burnley'].tail(20)

,date,comp,season,round,HT,AT,home points,away points,home GF,away GF,HT GS,AT GS,home GA,away GA,HT GC,AT GC,home xG,away xG,home xGA,away xGA,HT AdjGD,AT AdjGD,HT AdjGD form 5,AT AdjGD form 5,HT GD form 5,AT GD form 5,HT constant GD form 5,AT constant GD form 5,HT xGD form 5,AT xGD form 5,HT constant xGD form 5,AT constant xGD form 5,HT points form 5,AT points form 5,HT constant points form 5,AT constant points form 5,HT avg pos,AT avg pos,HT prev pos,AT prev pos,HT prev exp pos,AT prev exp pos,HT prev points,AT prev points,HT prev GD,AT prev GD,HT prev xGD,AT prev xGD,AT Away points form 10,AT Away constant points form 10,AT Away GF form 10,AT Away GA form 10,AT Away xG form 10,AT Away xGA form 10,AT Away GS form 10,AT Away GC form 10,HT Home points form 10,HT Home constant points form 10,HT Home GF form 10,HT Home GA form 10,HT Home xG form 10,HT Home xGA form 10,HT Home GS form 10,HT Home GC form 10,HT Market Value,AT Market Value,HT Wages,AT Wages
4614,2023-05-08,Championship,2022,Matchweek 46,Burnley,Cardiff City,0.9,0.0,2.24,-0.76,1.84,-0.46,1.02,4.02,1.32,3.62,1.44,-0.16,1.62,3.22,0.785,-3.815,-1.005,-1.785,-1.580000e+00,-1.98,-1.0,-1.0,-4.300000e-01,-1.59,-1.000000e+00,-1.00,0.48,0.42,1.0,1.0,15.000000,30.333333,18,39,15,33,35.0,15.9,-19.00,-99.88,-17.3,-59.0,0.36,1.0,0.340,2.420,0.470,2.550,0.405,2.485,0.69,1.0,1.240,1.420,1.120,1.510,1.180,1.465,193350000.0,5.020000e+07,NaN,NaN
4672,2023-08-11,Premier League,2023,Matchweek 1,Burnley,Manchester City,0.0,3.0,0.00,3.00,0.15,2.45,3.00,0.00,2.45,0.15,0.30,1.90,1.90,0.30,-2.300,2.300,-0.625,0.550,-9.800000e-01,0.80,-1.0,0.8,-2.700000e-01,0.30,-1.000000e+00,0.30,0.60,2.00,1.0,2.0,18.666667,1.000000,21,1,21,1,30.3,89.0,-29.88,61.00,-29.8,46.4,2.00,2.0,1.900,0.800,1.960,1.080,1.930,0.940,0.69,1.0,1.240,1.420,1.190,1.550,1.215,1.485,273480000.0,1.460000e+09,740500.0,3866000.0
4733,2023-08-27,Premier League,2023,Matchweek 3,Burnley,Aston Villa,0.0,3.0,1.00,3.00,0.85,2.75,3.00,1.00,2.75,0.85,0.70,2.50,2.50,0.70,-1.900,1.900,-0.882,0.460,-1.224000e+00,0.40,-1.4,0.4,-5.400000e-01,0.52,-1.120000e+00,0.52,0.54,2.00,0.8,2.0,18.666667,10.666667,21,7,21,9,30.3,61.0,-29.88,5.00,-29.8,-2.3,1.20,1.2,1.100,1.400,1.230,1.830,1.165,1.615,0.60,0.9,1.216,1.618,1.236,1.538,1.226,1.578,273480000.0,7.105000e+08,740500.0,2252885.0
4741,2023-09-02,Premier League,2023,Matchweek 4,Burnley,Tottenham,0.0,3.0,2.00,5.00,1.65,3.60,5.00,2.00,3.60,1.65,1.30,2.20,2.20,1.30,-1.950,1.950,-0.989,0.630,-1.068000e+00,1.00,-1.6,1.0,-9.100000e-01,0.26,-1.280000e+00,0.26,0.54,2.00,0.6,2.0,18.666667,6.333333,21,8,21,7,30.3,60.0,-29.88,7.00,-29.8,7.8,0.90,0.9,1.800,2.400,1.620,1.700,1.710,2.050,0.51,0.8,1.192,1.716,1.202,1.596,1.197,1.656,273480000.0,8.385000e+08,740500.0,2260000.0
4795,2023-09-23,Premier League,2023,Matchweek 6,Burnley,Manchester Utd,0.0,3.0,0.00,1.00,0.55,1.00,1.00,0.00,1.00,0.55,1.10,1.00,1.00,1.10,-0.450,0.450,-1.093,-0.410,-1.356000e+00,-0.80,-1.8,-0.8,-8.300000e-01,-0.02,-1.100000e+00,-0.02,0.38,1.20,0.4,1.2,18.666667,3.666667,21,3,21,6,30.3,75.0,-29.88,15.00,-29.8,17.2,1.00,1.0,0.800,1.800,1.480,2.010,1.140,1.905,0.42,0.7,1.168,2.114,1.278,1.694,1.223,1.904,273480000.0,8.087500e+08,740500.0,3956846.0
4851,2023-10-07,Premier League,2023,Matchweek 8,Burnley,Chelsea,0.0,3.0,1.00,4.00,0.85,2.95,4.00,1.00,2.95,0.85,0.70,1.90,1.90,0.70,-2.100,2.100,-0.870,0.800,-1.000000e+00,0.60,-1.0,0.6,-7.400000e-01,1.00,-7.400000e-01,1.00,0.80,1.40,0.8,1.4,18.666667,6.333333,21,12,21,10,30.3,44.0,-29.88,-9.00,-29.8,-2.8,1.00,1.0,1.100,1.600,1.430,1.700,1.265,1.650,0.39,0.6,1.144,2.012,1.224,1.652,1.184,1.832,273480000.0,1.010000e+09,740500.0,3020000.0
4931,2023-11-04,Premier League,2023,Matchweek 11,Burnley,Crystal Palace,0.0,3.0,0.00,2.00,0.55,1.65,2.00,0.00,1.65,0.55,1.10,1.30,1.30,1.10,-1.100,1.100,-1.420,-0.660,-1.600000e+00,-0.80,-1.6,-0.8,-1.240000e+00,-0.52,-1.240000e+00,-0.52,0.60,1.00,0.6,1.0,18.666667,12.333333,21,11,21,12,30.3,45.0,-29.88,-9.00,-29.8,-8.9,1.40,1.4,1.300,1.400,1.270,1.390,1.285,1.395,0.30,0.5,0.920,2.310,1.020,1.710,0.970,2.010,273480000.0,4.468300e+08,740500.0,1327885.0
4976,2023-11-25,Premier League,2023,Matchweek 13,Burnley,West Ham,0.0,3.0,1.00,2.00,1.15,1.45,2.00,1.00,1.45,1.15,1.30,0.90,0.90,1.30,-0.300,0.300,-1.620,-0.530,-2.200000e+00,-0.80,-2.2,-0.8,-1.040000e+00,-0.26,-1.040000e+00,-0.26,0.00,0.80,0.0,0.8,18.666667,9.000000,21,14,21,11,30.3,40.0,-29.88,-13.00,-29.8,-3.8,0.70,0.7,1.400,2.400,1.280,1.980,1.340,2.190,0.21,0.4,0.696,2.408,0.896,1.688,0.796,2.048,273480000.0,4.875000e+08,740500.0,1833000.0
5010,2023-12-02,Premier League,2023,Matchweek 14,Burnley,Sheffield Utd,3.0,0.0,5.00,0.00,3.40,0.20,0.00,5.00,0.20,3.40,1.80,0.40,0.40,1.80,3.200,-3.200,-1.260,-1.220,-1.800000e+00,-1.40,-1.8,-1.4,-7.200000e-01,-1.04,-7.200000e-01,-1.04,0.00,0.80,0.0,0.8,18.666667,22.333333,21,22,21,22,30.3,27.3,-29.88,-47.88,-29.8,-29.9,0.28,0.5,0.396,2.308,0.626,1.918,0.511,2.113,0.18,0.3,0.872,2.506,0.982,1.646,0.927,2.076,273480000.0,1.524500e+08,740500.0,553000.0
5074,2023-12-16,Premier League,2023,Matchweek 17,Burnley,Everton,0.0,3.0,0.00,2.00,0.35,1.70,2.00,0.00,1.70,0.35,0.70,1.40,1.40,0.70,-1.350,1.350,-0.060,0.560,2.000000e-01,0.80,0.2,0.8,-3.200000e-01,0.32,-3.200000e-01,0.32,0.80,2.40,0.8,2.4,18.666667,14.333333,21,17,21,16,30.3,36.0,-29.88,-23.00,-29.8,-20.2,1.80,1.8,1.800,1.500,1.550,1.910,1.675,1.705,0.39,0.5,1.248,2.404,1.098,1.544,1.173,1.974,273480000.0,3.917500e+08,740500.0,1518808.0
5116,2023-12-26,Premier League,2023,Matchweek 19,Burnley,Liverpool,0.0,3.0,0.00,2.00,0.40,1.90,2.00,0.00,1.90,0.40,0.80,1.80,1.80,0.80,-1.500,1.500,0.190,0.690,8.000000e-01,0.80,0.8,0.8,-4.200000e-01,0.58,-4.200000e-01,0.58,1.40,2.20,1.4,2.2,18.666667,3.333333,21,5,21,5,30.3,67.0,-29.88,28.00,-29.8,21.6,1.70,1.7,1.900,1.400,1.840,1.510,1.870,1.455,0.39,0.4,1.224,2.302,1.044,1.512,1.134,1.907,273480000.0,9.558500e+08,740500.0,2620000.0
5170,2024-01-12,Premier League,2023,Matchweek 21,Burnley,Luton Town,1.0,1.0,1.00,1.00,1.05,0.95,1.00,1.00,0.95,1.05,1.10,0.90,0.90,1.10,0.100,-0.100,-0.960,-0.500,-6.000000e-01,-0.20,-0.6,-0.2,-1.320000e+00,-0.80,-1.320000e+00,-0.80,0.80,1.20,0.8,1.2,18.666667,27.000000,21,23,21,25,30.3,24.0,-29.88,-63.88,-29.8,-43.3,0.73,0.8,1.024,2.202,0.804,2.542,0.914,2.372,0.30,0.3,1.000,2.400,0.980,1.530,0.990,1.965,273480000.0,1.409000e+08,740500.0,472500.0
5224,2024-02-03,Premier League,2023,Matchweek 23,Burnley,Fulham,1.0,1.0,2.00,2.00,1.90,1.75,2.00,2.00,1.75,1.90,1.80,1.50,1.50,1.80,0.150,-0.150,-0.700,-0.770,-6.000000e-01,-1.00,-0.6,-1.0,-8.000000e-01,-0.54,-8.000000e-01,-0.54,0.80,0.80,0.8,0.8,18.666667,16.333333,21,10,21,14,30.3,52.0,-29.88,2.00,-29.8,-17.3,0.30,0.3,0.800,2.400,0.780,2.120,0.790,2.260,0.40,0.4,1.100,2.200,1.060,1.430,1.080,1.815,273480000.0,3.843500e+08,740500.0,1282500.0
5281,2024-02-17,Premier League,2023,Matchweek 25,Burnley,Arsenal,0.0,3.0,0.00,5.00,0.15,3.65,5.00,0.00,3.65,0.15,0.30,2.30,2.30,0.30,-3.500,3.500,-0.830,2.360,-1.000000e+00,2.60,-1.0,2.6,-6.600000e-01,2.12,-6.600000e-01,2.12,0.40,2.40,0.4,2.4,18.666667,5.000000,21,2,21,3,30.3,84.0,-29.88,45.00,-29.8,29.3,1.70,1.7,2.100,1.100,1.730,0.800,1.915,0.950,0.50,0.5,1.200,2.100,1.170,1.330,1.185,1.715,273480000.0,1.200000e+09,740500.0,3193000.0
5344,2024-03-03,Premier League,2023,Matchweek 27,Burnley,Bournemouth,0.0,3.0,0.00,2.00,0.75,1.55,2.00,0.00,1.55,0.75,1.50,1.10,1.10,1.50,-0.800,0.800,-1.780,-0.290,-2.400000e+00,-0.60,-2.4,-0.6,-1.160000e+00,0.02,-1.160000e+00,0.02,0.20,0.60,0.2,0.6,18.666667,21.000000,21,15,21,20,30.3,39.0,-29.88,-34.00,-29.8,-25.4,1.40,1.4,1.700,2.100,1.630,1.570,1.665,1.835,0.50,0.5,1.000,2.100,1.070,1.340,1.035,1.720,273480000.0,4.019000e+08,740500.0,1054500.0
5383,2024-03-16,Premier League,2023,Matchweek 29,Burnley,Brentford,3.0,0.0,2.00,1.00,2.40,1.05,1.00,2.00,1.05,2.40,2.80,1.10,1.10,2.80,1.350,-1.350,-1.880,-1.120,-2.400000e+00,-1.40,-2.4,-1.4,-1.360000e+00,-0.84,-1.360000e+00,-0.84,0.20,0.20,0.2,0.2,18.666667,15.000000,21,9,21,8,30.3,59.0,-29.88,12.00,-29.8,6.6,0.60,0.6,1.100,1.900,1.310,1.610,1.205,1.755,0.50,0.5,1.000,2.200,1.110,1.350,1.055,1.775,273480000.0,4.290300e+08,740500.0,768000.0
5431,2024-04-02,Premier League,2023,Matchweek 31,Burnley,Wolves,1.0,1.0,1.00,1.00,1.15,0.95,1.00,1.00,0.95,1.15,1.30,0.90,0.90,1.30,0.200,-0.200,-0.820,-0.370,-8.000000e-01,-0.40,-0.8,-0.4,-8.400000e-01,-0.34,-8.400000e-01,-0.34,1.00,1.80,1.0,1.8,18.666667,12.000000,21,13,21,18,30.3,41.0,-29.88,-27.00,-29.8,-23.3,1.00,1.0,1.400,1.900,1.360,1.740,1.380,1.820,0.80,0.8,1.100,1.900,1.320,1.270,1.210,1.585,273480000.0,4.432300e+08,740500.0,1035000.0
5479,2024-04-13,Premier League,2023,Matchweek 33,Burnley,Brighton,1.0,1.0,1.00,1.00,1.35,0.95,1.00,1.00,0.95,1.35,1.70,0.90,0.90,1.70,0.400,-0.400,-0.230,-1.100,-1.776357e-16,-1.20,0.0,-1.2,-4.600000e-01,-1.00,-4.600000e-01,-1.00,1.20,0.80,1.2,0.8,18.666667,10.333333,21,6,21,4,30.3,62.0,-29.88,19.00,-29.8,23.4,0.60,0.6,1.000,1.700,1.320,1.640,1.160,1.670,0.90,0.9,1.200,1.800,1.340,1.230,1.270,1.515,273480000.0,5.244000e+08,740500.0,1200000.0
5551,2024-05-04,Premier League,2023,Matchweek 36,Burnley,Newcastle Utd,0.0,3.0,1.00,4.00,1.00,3.70,4.00,1.00,3.70,1.00,1.00,3.40,3.40,1.00,-2.700,2.700,0.200,1.090,4.000000e-01,1.40,0.4,1.4,2.664535e-16,0.78,8.881784e-17,0.78,1.20,2.00,1.2,2.0,18.666667,9.000000,21,4,21,2,30.3,71.0,-29.88,35.00,-29.8,32.2,0.90,0.9,1.300,2.400,1.060,2.490,1.180,2.445,1.00,1.0,1.200,1.700,1.380,1.230,1.290,1.465,273480000.0,6.526500e+08,740500.0,1625000.0
5585,2024-05-19,Premier League,2023,Matchweek 38,Burnley,Nott'ham Forest,0.0,3.0,1.00,2.00,1.10,1.85,2.00,1.00,1.85,1.10,1.20,1.70,1.70,1.20,-0.750,0.750,-0.540,-0.130,-2.000000e-01,-0.60,-0.2,-0.6,-8.800000e-01,0.34,-8.800000e-01,0.34,1.00,0.80,1.0,0.8,18.666667,25.666667,21,16,21,19,30.3,38.0,-29.88,-30.00,-29.8,-24.7,0.90,0.9,1.400,1.800,1.570,1.470,1.485,1.635,0.70,0.7,0.800,2.100,1.300,1.530,1.050,1.815,273480000.0,5.013500e+08,740500.0,1385577.0

In [16]:
df.columns

Index(['date', 'comp', 'season', 'round', 'HT', 'AT', 'home points',
       'away points', 'home GF', 'away GF', 'HT GS', 'AT GS', 'home GA',
       'away GA', 'HT GC', 'AT GC', 'home xG', 'away xG', 'home xGA',
       'away xGA', 'HT AdjGD', 'AT AdjGD', 'HT AdjGD form 5',
       'AT AdjGD form 5', 'HT GD form 5', 'AT GD form 5',
       'HT constant GD form 5', 'AT constant GD form 5', 'HT xGD form 5',
       'AT xGD form 5', 'HT constant xGD form 5', 'AT constant xGD form 5',
       'HT points form 5', 'AT points form 5', 'HT constant points form 5',
       'AT constant points form 5', 'HT avg pos', 'AT avg pos', 'HT prev pos',
       'AT prev pos', 'HT prev exp pos', 'AT prev exp pos', 'HT prev points',
       'AT prev points', 'HT prev GD', 'AT prev GD', 'HT prev xGD',
       'AT prev xGD', 'AT Away points form 10',
       'AT Away constant points form 10', 'AT Away GF form 10',
       'AT Away GA form 10', 'AT Away xG form 10', 'AT Away xGA form 10',
       'AT Away GS form 10', 'AT Away GC form 10', 'HT Home points form 10',
       'HT Home constant points form 10', 'HT Home GF form 10',
       'HT Home GA form 10', 'HT Home xG form 10', 'HT Home xGA form 10',
       'HT Home GS form 10', 'HT Home GC form 10', 'HT Market Value',
       'AT Market Value', 'HT Wages', 'AT Wages'],
      dtype='object')

In [17]:
result = []
for x in range(len(df)):
    if df['home points'][x] == 0:
        result.append('AW')
    elif df['away points'][x] == 0:
        result.append('HW')
    elif pd.isna(df['home points'][x]):
        result.append('NaN')
    else:
        result.append('D')

df['result'] = result

In [18]:
df_expected = df[['date','comp', 'season', 'round','HT', 'AT','result','home points','away points', 'home GF', 'away GF',
                  'HT xGD form 5', 'AT xGD form 5','HT constant xGD form 5', 'AT constant xGD form 5', 
                  'HT Home xG form 10','HT Home xGA form 10','AT Away xG form 10', 'AT Away xGA form 10',
                  'HT prev exp pos', 'AT prev exp pos','HT prev xGD','AT prev xGD']]

In [19]:
df_actual = df[['date','comp', 'season', 'round','HT', 'AT','result','home points','away points', 'home GF', 'away GF',
                'HT points form 5', 'AT points form 5','HT constant points form 5','AT constant points form 5','HT GD form 5', 'AT GD form 5','HT constant GD form 5', 'AT constant GD form 5',
                'HT Home points form 10','HT Home constant points form 10','AT Away points form 10','AT Away constant points form 10','HT Home GF form 10', 'HT Home GA form 10','AT Away GF form 10', 'AT Away GA form 10',
                'HT avg pos', 'AT avg pos', 'HT prev pos', 'AT prev pos','HT prev points','AT prev points', 'HT prev GD', 'AT prev GD',
                'HT Market Value', 'AT Market Value', 'HT Wages', 'AT Wages']]

In [20]:
df_mixed = df[['date', 'comp', 'season', 'round', 'HT', 'AT', 'result','home points','away points', 'home GF', 'away GF','HT GS', 'AT GS', 'home GA','away GA', 'HT GC', 'AT GC', 'home xG', 'away xG', 'home xGA','away xGA',
               'HT AdjGD', 'AT AdjGD', 'HT AdjGD form 5', 'AT AdjGD form 5','HT GD form 5', 'AT GD form 5','HT constant GD form 5', 'AT constant GD form 5', 'HT xGD form 5','AT xGD form 5', 'HT constant xGD form 5', 'AT constant xGD form 5','HT points form 5', 'AT points form 5', 'HT constant points form 5','AT constant points form 5',
               'HT avg pos', 'AT avg pos', 'HT prev pos','AT prev pos', 'HT prev exp pos', 'AT prev exp pos', 'HT prev points','AT prev points', 'HT prev GD', 'AT prev GD', 'HT prev xGD','AT prev xGD',
               'AT Away GS form 10', 'AT Away GC form 10','AT Away points form 10','AT Away constant points form 10', 'AT Away GF form 10','AT Away GA form 10', 'AT Away xG form 10', 'AT Away xGA form 10','HT Home points form 10', 'HT Home constant points form 10','HT Home GF form 10', 'HT Home GA form 10', 'HT Home xG form 10','HT Home xGA form 10','HT Home GS form 10', 'HT Home GC form 10',
               'HT Market Value', 'AT Market Value', 'HT Wages', 'AT Wages']]

In [21]:
#df_simple = df[['date','comp', 'season', 'round','HT', 'AT','target','home points', 'away points', 'HT points form 5', 'AT points form 5','HT avg pos', 'AT avg pos']]

In [22]:
#df_simple.to_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\MATCH DATASET SIMPLE WITH FUTURE GOALS MODEL.xlsx", index=False)

In [23]:
df_actual.to_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Actual Dataset.xlsx")

In [24]:
df_expected.to_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Expected Dataset.xlsx")

In [25]:
df_mixed.to_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Big Dataset.xlsx")