In [1]:
import pandas as pd
from collections import defaultdict

In [2]:
df = pd.read_csv(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Original Match Dataset.csv", index_col=0)

In [3]:
future_df = pd.read_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\2024-25 Prem Fixtures Cleaned and Merged.xlsx", index_col=0)

In [4]:
df.columns

Index(['date', 'time', 'comp', 'round', 'day', 'venue', 'result', 'gf', 'ga',
       'opponent', 'xg', 'xga', 'poss', 'attendance', 'captain', 'formation',
       'referee', 'match report', 'notes', 'season', 'team'],
      dtype='object')

In [5]:
future_df

                Team           Opponent  Game Week Venue       Date
0    AFC Bournemouth  Nottingham Forest          1  Away 2024-08-20
1    AFC Bournemouth   Newcastle United          2  Home 2024-08-27
2    AFC Bournemouth            Everton          3  Away 2024-09-03
3    AFC Bournemouth            Chelsea          4  Home 2024-09-10
4    AFC Bournemouth          Liverpool          5  Away 2024-09-17
..               ...                ...        ...   ...        ...
755           Wolves     Leicester City         34  Home 2025-04-08
756           Wolves           Man City         35  Away 2025-04-15
757           Wolves           Brighton         36  Home 2025-04-22
758           Wolves     Crystal Palace         37  Away 2025-04-29
759           Wolves          Brentford         38  Home 2025-05-06

[760 rows x 5 columns]

In [6]:
future_df.rename(columns={'Team': 'team', 'Game Week': 'round','Date':'date','Venue':'venue','Opponent':'opponent'}, inplace=True)
future_df['round'] = future_df['round'].apply(lambda gw: f"Matchweek {gw}")
future_df['comp'] = 'Premier League'
future_df['season'] = 2024
future_df = future_df[['date','comp','season','round','venue','opponent','team']]

In [7]:
class MissingDict(dict):
    __missing__ = lambda self, key: key

map_values = {"AFC Bournemouth":"Bournemouth","Brighton and Hove Albion": "Brighton", "Huddersfield Town":"Huddersfield","Manchester United": "Manchester Utd","Man Utd": "Manchester Utd","Man City": "Manchester City", "Newcastle United": "Newcastle Utd", "Nottingham Forest":"Nott'ham Forest","Tottenham Hotspur": "Tottenham","Spurs": "Tottenham","Sheffield United":"Sheffield Utd", "West Ham United": "West Ham","West Bromwich Albion":"West Brom", "Wolverhampton Wanderers": "Wolves","Wycombe Wanderers":"Wycombe","Sheffield Wednesday":"Sheffield Weds","Queens Park Rangers":"QPR","Rotherham United":"Rotherham Utd","Preston North End":"Preston","Peterborough United":"P'borough Utd","Charlton Athletic":"Charlton Ath","Bolton Wanderers":"Bolton","Blackburn Rovers":"Blackburn"} 
mapping = MissingDict(**map_values)

In [8]:
future_df['team'] = future_df['team'].map(mapping)
future_df['opponent'] = future_df['opponent'].map(mapping)

In [9]:
future_df['team'].unique()

array(['Bournemouth', 'Arsenal', 'Aston Villa', 'Brentford', 'Brighton',
       'Chelsea', 'Crystal Palace', 'Everton', 'Fulham', 'Ipswich Town',
       'Leicester City', 'Liverpool', 'Manchester City', 'Manchester Utd',
       'Newcastle Utd', "Nott'ham Forest", 'Southampton', 'Tottenham',
       'West Ham', 'Wolves'], dtype=object)

In [10]:
df = pd.concat([df, future_df], ignore_index=True)

In [11]:
df.drop(columns=["day", "captain", "poss", "attendance", "formation", "referee","match report","notes","time"], inplace=True)
df["date"] = pd.to_datetime(df["date"])

In [12]:
df["new_team"] = df["team"].map(mapping)

In [13]:
df['new_team'].unique()

array(['Leicester City', 'Ipswich Town', 'Leeds United', 'Southampton',
       'West Brom', 'Norwich City', 'Hull City', 'Middlesbrough',
       'Coventry City', 'Preston', 'Bristol City', 'Cardiff City',
       'Millwall', 'Swansea City', 'Watford', 'Sunderland', 'Stoke City',
       'QPR', 'Blackburn', 'Sheffield Weds', 'Plymouth Argyle',
       'Birmingham City', 'Huddersfield', 'Rotherham Utd', 'Burnley',
       'Sheffield Utd', 'Luton Town', 'Reading', 'Blackpool',
       'Wigan Athletic', 'Fulham', 'Bournemouth', "Nott'ham Forest",
       "P'borough Utd", 'Derby County', 'Barnsley', 'Brentford',
       'Wycombe', 'Charlton Ath', 'Aston Villa', 'Bolton', 'Wolves',
       'Burton Albion', 'Manchester City', 'Arsenal', 'Liverpool',
       'Tottenham', 'Chelsea', 'Newcastle Utd', 'Manchester Utd',
       'West Ham', 'Crystal Palace', 'Brighton', 'Everton'], dtype=object)

In [14]:
# Fixing the Brentford v Bolton Cancelled Match
df.loc[6024, 'xg'] = 1.0
df.loc[6024, 'xga'] = 1.0
df.loc[6576, 'xg'] = 1.0
df.loc[6576, 'xga'] = 1.0

In [15]:
df

,date,comp,round,venue,result,gf,ga,opponent,xg,xga,season,team,new_team
0,2023-08-06,Championship,Matchweek 1,Home,W,2.0,1.0,Coventry City,1.5,1.8,2023,Leicester City,Leicester City
1,2023-08-12,Championship,Matchweek 2,Away,W,1.0,0.0,Huddersfield,1.4,1.2,2023,Leicester City,Leicester City
2,2023-08-19,Championship,Matchweek 3,Home,W,2.0,1.0,Cardiff City,0.7,1.1,2023,Leicester City,Leicester City
3,2023-08-26,Championship,Matchweek 4,Away,W,2.0,1.0,Rotherham Utd,1.4,0.6,2023,Leicester City,Leicester City
4,2023-09-02,Championship,Matchweek 5,Home,L,0.0,1.0,Hull City,1.2,0.3,2023,Leicester City,Leicester City
...,...,...,...,...,...,...,...,...,...,...,...,...,...
13803,2025-04-08,Premier League,Matchweek 34,Home,NaN,NaN,NaN,Leicester City,NaN,NaN,2024,Wolves,Wolves
13804,2025-04-15,Premier League,Matchweek 35,Away,NaN,NaN,NaN,Manchester City,NaN,NaN,2024,Wolves,Wolves
13805,2025-04-22,Premier League,Matchweek 36,Home,NaN,NaN,NaN,Brighton,NaN,NaN,2024,Wolves,Wolves
13806,2025-04-29,Premier League,Matchweek 37,Away,NaN,NaN,NaN,Crystal Palace,NaN,NaN,2024,Wolves,Wolves
13807,2025-05-06,Premier League,Matchweek 38,Home,NaN,NaN,NaN,Brentford,NaN,NaN,2024,Wolves,Wolves

In [16]:
# Add Points and Goals Difference
df['gf'] = df['gf'].astype(float)
df['ga'] = df['ga'].astype(float)
df["xGD"] = df["xg"] - df["xga"]
df["GD"] = df["gf"] - df["ga"]
#df["GD"] = df["GD"].astype(int)

points = []
for x in range(len(df)):
    points.append(3 if df["result"][x] == "W" else 1 if df["result"][x] == "D" else 0 if df["result"][x] == "L" else float("nan"))

df["points"] = points

In [17]:
def set_league_diff(df, point_weight, xGD_weight, GD_weight, GF_weight, GA_weight):   
    league_diff = []
    xGD_league_diff = []
    GD_league_diff = []
    GF_league_diff = []
    GA_league_diff = []
    xG_league_diff = []
    xGA_league_diff = []
    for x in range(len(df)):
        if df['comp'][x] == 'Championship':
            league_diff.append(point_weight)
            xGD_league_diff.append(xGD_weight)
            GD_league_diff.append(GD_weight)
            GF_league_diff.append(GF_weight)
            GA_league_diff.append(GA_weight)
            xG_league_diff.append(GF_weight)
            xGA_league_diff.append(GA_weight)
        else:
            league_diff.append(1)
            xGD_league_diff.append(0)
            GD_league_diff.append(0)
            GF_league_diff.append(0)
            GA_league_diff.append(0)
            xG_league_diff.append(0)
            xGA_league_diff.append(0)

    df["league_diff"] = league_diff
    df["xGD_league_diff"] = xGD_league_diff
    df["GD_league_diff"] = GD_league_diff
    df["GF_league_diff"] = GF_league_diff
    df["GA_league_diff"] = GA_league_diff
    df["xG_league_diff"] = xG_league_diff
    df["xGA_league_diff"] = xGA_league_diff
    return df

def cal_weighted_metrics(df):
    df["league_weighted_points"] = df["points"] * df["league_diff"]
    df["league_weighted_xGD"] = df["xGD"] + df["xGD_league_diff"]
    df["league_weighted_GD"] = df["GD"] + df["GD_league_diff"]
    df["league_weighted_GF"] = df["gf"] + df["GF_league_diff"]
    df["league_weighted_GA"] = df["ga"] + df["GA_league_diff"]
    df["league_weighted_xG"] = df["xg"] + df["xG_league_diff"]
    df["league_weighted_xGA"] = df["xga"] + df["xGA_league_diff"]
    return df

In [18]:
point_weight = 0.30
xGD_weight = -1.25
GD_weight = -1.78
GF_weight = -0.76
GA_weight = +1.02
df = set_league_diff(df, point_weight, xGD_weight, GD_weight, GF_weight, GA_weight)
df = cal_weighted_metrics(df)

In [19]:
def cal_season_points(df, season):
    # Filter the dataframe based on the season#
    team_points = defaultdict(int)
    team_xGD = defaultdict(int)
    df = df[df['season'] == season]

    # Iterate through the rows
    for _, row in df.iterrows():
        team = row['new_team']
        team_xGD[team] += (row['league_weighted_xGD'])
        result = row['result']
        league_diff = row['league_diff']

        if result == 'W':
            team_points[team] += (3 * league_diff)  # Home win, add 3 points to home team
        elif result == 'D':
            team_points[team] += (1 * league_diff)  # Draw, add 1 point to both teams
        else:
            team_points[team] += 0  # Away win, add 3 points to away team
    
    points_df = pd.DataFrame(list(team_points.items()), columns=['Team', 'Points'])
    xGD_df = pd.DataFrame(list(team_xGD.items()), columns=['Team', 'xGD'])
    new_df = pd.merge(points_df, xGD_df, on='Team')
    new_df = new_df.sort_values(by='Points', ascending=False)
    new_df = new_df.reset_index(drop=True)
    return new_df

In [20]:
def cal_season_finish(df, season, league):
    # Filter the dataframe based on the season#
    team_points = defaultdict(int)
    team_xGD = defaultdict(int)
    team_GD = defaultdict(int)
    df = df[df['season'] == season]
    df = df[df['comp'] == league]

    # Iterate through the rows
    for _, row in df.iterrows():
        team = row['new_team']
        team_points[team] += (row['league_weighted_points'])
        team_xGD[team] += (row['league_weighted_xGD'])
        team_GD[team] += (row['league_weighted_GD'])
    
    points_df = pd.DataFrame(list(team_points.items()), columns=['Team', 'Points'])
    xGD_df = pd.DataFrame(list(team_xGD.items()), columns=['Team', 'xGD'])
    GD_df = pd.DataFrame(list(team_GD.items()), columns=['Team', 'GD'])
    new_df = pd.merge(points_df, xGD_df, on='Team')
    new_df = pd.merge(new_df, GD_df, on='Team')
    new_df = new_df.sort_values(by=['Points','GD'], ascending=False)
    if league == 'Premier League':
        new_df['Actual Position'] = range(1, len(new_df) + 1)
        new_df['Expected Position'] = new_df['xGD'].rank(ascending=False)
    elif league == 'Championship':
        new_df['Actual Position'] = range(21, len(new_df) + 21)
        new_df['Expected Position'] = (new_df['xGD'].rank(ascending=False)) + 20
    new_df['Points'] = points_df['Points']
    new_df['xGD'] = xGD_df['xGD']
    new_df['GD'] = GD_df['GD']
    new_df = new_df.sort_values(by='Actual Position', ascending=True)
    new_df = new_df.reset_index(drop=True)
    return new_df

In [21]:
prem_2023 = cal_season_finish(df, 2023, 'Premier League')
prem_2022 = cal_season_finish(df, 2022, 'Premier League')
prem_2021 = cal_season_finish(df, 2021, 'Premier League')
prem_2020 = cal_season_finish(df, 2020, 'Premier League')
prem_2019 = cal_season_finish(df, 2019, 'Premier League')
prem_2018 = cal_season_finish(df, 2018, 'Premier League')
prem_2017 = cal_season_finish(df, 2017, 'Premier League')
champ_2023 = cal_season_finish(df, 2023, 'Championship')
champ_2022 = cal_season_finish(df, 2022, 'Championship')
champ_2021 = cal_season_finish(df, 2021, 'Championship')
champ_2020 = cal_season_finish(df, 2020, 'Championship')
champ_2019 = cal_season_finish(df, 2019, 'Championship')
champ_2018 = cal_season_finish(df, 2018, 'Championship')
champ_2017 = cal_season_finish(df, 2017, 'Championship')
points_2017 = pd.concat([prem_2017, champ_2017])
points_2018 = pd.concat([prem_2018, champ_2018])
points_2019 = pd.concat([prem_2019, champ_2019])
points_2020 = pd.concat([prem_2020, champ_2020])
points_2021 = pd.concat([prem_2021, champ_2021])
points_2022 = pd.concat([prem_2022, champ_2022])
points_2023 = pd.concat([prem_2023, champ_2023])

In [22]:
def add_previous_points(df, season, point_df):
    for team, points, xGD, GD, position, xposition in point_df.values:
        df = df.loc[df['season'] == season]
        df.loc[df['new_team'] == team, 'new_team_previous_points'] = points
        df.loc[df['new_team'] == team, 'new_team_previous_xGD'] = xGD
        df.loc[df['new_team'] == team, 'new_team_previous_GD'] = GD
        df.loc[df['new_team'] == team, 'new_team_previous_position'] = position
        df.loc[df['new_team'] == team, 'new_team_previous_expected_position'] = xposition
    return df

In [23]:
df2017 = df[df['season'] == 2017]
df2018 = add_previous_points(df, 2018, points_2017)
df2019 = add_previous_points(df, 2019, points_2018)
df2020 = add_previous_points(df, 2020, points_2019)
df2021 = add_previous_points(df, 2021, points_2020)
df2022 = add_previous_points(df, 2022, points_2021)
df2023 = add_previous_points(df, 2023, points_2022)
df2024 = add_previous_points(df, 2024, points_2023)

C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_points'] = points
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_xGD'] = xGD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_GD'] = GD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_position'] = position
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_expected_position'] = xposition
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_points'] = points
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_xGD'] = xGD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_GD'] = GD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_position'] = position
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_expected_position'] = xposition
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_points'] = points
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_xGD'] = xGD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_GD'] = GD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_position'] = position
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_expected_position'] = xposition
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_points'] = points
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_xGD'] = xGD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_GD'] = GD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_position'] = position
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_expected_position'] = xposition
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_points'] = points
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_xGD'] = xGD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_GD'] = GD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_position'] = position
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_expected_position'] = xposition
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_points'] = points
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_xGD'] = xGD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_GD'] = GD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_position'] = position
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_expected_position'] = xposition
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_points'] = points
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_xGD'] = xGD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_GD'] = GD
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_position'] = position
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\1147446800.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.loc[df['new_team'] == team, 'new_team_previous_expected_position'] = xposition

In [24]:
df = pd.concat([df2017,df2018, df2019, df2020, df2021, df2022, df2023, df2024])
df.reset_index(drop=True, inplace=True)

In [25]:
df.columns

Index(['date', 'comp', 'round', 'venue', 'result', 'gf', 'ga', 'opponent',
       'xg', 'xga', 'season', 'team', 'new_team', 'xGD', 'GD', 'points',
       'league_diff', 'xGD_league_diff', 'GD_league_diff', 'GF_league_diff',
       'GA_league_diff', 'xG_league_diff', 'xGA_league_diff',
       'league_weighted_points', 'league_weighted_xGD', 'league_weighted_GD',
       'league_weighted_GF', 'league_weighted_GA', 'league_weighted_xG',
       'league_weighted_xGA', 'new_team_previous_points',
       'new_team_previous_xGD', 'new_team_previous_GD',
       'new_team_previous_position', 'new_team_previous_expected_position'],
      dtype='object')

In [26]:
df_rest_champ = df[df["season"] != 2017][df['comp'] == 'Championship']
df_rest_prem = df[(df["season"] != 2017) & (df["season"] != 2024)][df['comp'] == 'Premier League']
df_rest_champ.reset_index(drop=True, inplace=True)
df_rest_prem.reset_index(drop=True, inplace=True)
df_future = df[df["season"] == 2024]
df_future.reset_index(drop=True, inplace=True)

C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\366291957.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_rest_champ = df[df["season"] != 2017][df['comp'] == 'Championship']
C:\Users\dmsta\AppData\Local\Temp\ipykernel_16768\366291957.py:2: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_rest_prem = df[(df["season"] != 2017) & (df["season"] != 2024)][df['comp'] == 'Premier League']

In [27]:
# Fill in the missing values for the previous season
df_rest_champ['new_team_previous_points'].fillna(15, inplace=True)
df_rest_champ['new_team_previous_xGD'].fillna(-80, inplace=True)
df_rest_champ['new_team_previous_GD'].fillna(-80, inplace=True)
df_rest_champ['new_team_previous_position'].fillna(45, inplace=True)
df_rest_champ['new_team_previous_expected_position'].fillna(45, inplace=True)
df_rest_prem['new_team_previous_points'].fillna(30, inplace=True)
df_rest_prem['new_team_previous_xGD'].fillna(0, inplace=True)
df_rest_prem['new_team_previous_GD'].fillna(0, inplace=True)
df_rest_prem['new_team_previous_position'].fillna(21, inplace=True)
df_rest_prem['new_team_previous_expected_position'].fillna(21, inplace=True)

In [28]:
df_rest = pd.concat([df_rest_champ, df_rest_prem])
df = pd.concat([df2017, df_rest])
df = pd.concat([df, df_future])

In [29]:
df.reset_index(drop=True, inplace=True)
df.isnull().sum()

date                                      0
comp                                      0
round                                     0
venue                                     0
result                                  760
gf                                      760
ga                                      760
opponent                                  0
xg                                     1864
xga                                    1864
season                                    0
team                                      0
new_team                                  0
xGD                                    1864
GD                                      760
points                                  760
league_diff                               0
xGD_league_diff                           0
GD_league_diff                            0
GF_league_diff                            0
GA_league_diff                            0
xG_league_diff                            0
xGA_league_diff                           0
league_weighted_points                  760
league_weighted_xGD                    1864
league_weighted_GD                      760
league_weighted_GF                      760
league_weighted_GA                      760
league_weighted_xG                     1864
league_weighted_xGA                    1864
new_team_previous_points               1864
new_team_previous_xGD                  1864
new_team_previous_GD                   1864
new_team_previous_position             1864
new_team_previous_expected_position    1864
dtype: int64

In [30]:
pd.set_option('display.max_columns', None)
df

,date,comp,round,venue,result,gf,ga,opponent,xg,xga,season,team,new_team,xGD,GD,points,league_diff,xGD_league_diff,GD_league_diff,GF_league_diff,GA_league_diff,xG_league_diff,xGA_league_diff,league_weighted_points,league_weighted_xGD,league_weighted_GD,league_weighted_GF,league_weighted_GA,league_weighted_xG,league_weighted_xGA,new_team_previous_points,new_team_previous_xGD,new_team_previous_GD,new_team_previous_position,new_team_previous_expected_position
0,2017-08-05,Championship,Matchweek 1,Home,W,1.0,0.0,Middlesbrough,NaN,NaN,2017,Wolverhampton Wanderers,Wolves,NaN,1.0,3.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.9,NaN,-0.78,0.24,1.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2017-08-12,Championship,Matchweek 2,Away,W,2.0,0.0,Derby County,NaN,NaN,2017,Wolverhampton Wanderers,Wolves,NaN,2.0,3.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.9,NaN,0.22,1.24,1.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2017-08-15,Championship,Matchweek 3,Away,W,3.0,2.0,Hull City,NaN,NaN,2017,Wolverhampton Wanderers,Wolves,NaN,1.0,3.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.9,NaN,-0.78,2.24,3.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2017-08-19,Championship,Matchweek 4,Home,L,1.0,2.0,Cardiff City,NaN,NaN,2017,Wolverhampton Wanderers,Wolves,NaN,-1.0,0.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.0,NaN,-2.78,0.24,3.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2017-08-26,Championship,Matchweek 5,Away,D,0.0,0.0,Brentford,NaN,NaN,2017,Wolverhampton Wanderers,Wolves,NaN,0.0,1.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.3,NaN,-1.78,-0.76,1.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13803,2025-04-08,Premier League,Matchweek 34,Home,NaN,NaN,NaN,Leicester City,NaN,NaN,2024,Wolves,Wolves,NaN,NaN,NaN,1.0,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,-20.7,-15.0,15.0,17.0
13804,2025-04-15,Premier League,Matchweek 35,Away,NaN,NaN,NaN,Manchester City,NaN,NaN,2024,Wolves,Wolves,NaN,NaN,NaN,1.0,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,-20.7,-15.0,15.0,17.0
13805,2025-04-22,Premier League,Matchweek 36,Home,NaN,NaN,NaN,Brighton,NaN,NaN,2024,Wolves,Wolves,NaN,NaN,NaN,1.0,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,-20.7,-15.0,15.0,17.0
13806,2025-04-29,Premier League,Matchweek 37,Away,NaN,NaN,NaN,Crystal Palace,NaN,NaN,2024,Wolves,Wolves,NaN,NaN,NaN,1.0,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,-20.7,-15.0,15.0,17.0
13807,2025-05-06,Premier League,Matchweek 38,Home,NaN,NaN,NaN,Brentford,NaN,NaN,2024,Wolves,Wolves,NaN,NaN,NaN,1.0,0.00,0.00,0.00,0.00,0.00,0.00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,46.0,-20.7,-15.0,15.0,17.0

In [31]:
df['Adjusted GS'] = (df['league_weighted_GF'] * 0.5) + (df['league_weighted_xG'] * 0.5)
df['Adjusted GC'] = (df['league_weighted_GA'] * 0.5) + (df['league_weighted_xGA'] * 0.5)
df['Adjusted GD'] = (df['league_weighted_GD'] * 0.5) + (df['league_weighted_xGD'] * 0.5)

In [32]:
df[df['season'] == 2023]

,date,comp,round,venue,result,gf,ga,opponent,xg,xga,season,team,new_team,xGD,GD,points,league_diff,xGD_league_diff,GD_league_diff,GF_league_diff,GA_league_diff,xG_league_diff,xGA_league_diff,league_weighted_points,league_weighted_xGD,league_weighted_GD,league_weighted_GF,league_weighted_GA,league_weighted_xG,league_weighted_xGA,new_team_previous_points,new_team_previous_xGD,new_team_previous_GD,new_team_previous_position,new_team_previous_expected_position,Adjusted GS,Adjusted GC,Adjusted GD
7384,2023-08-06,Championship,Matchweek 1,Home,W,2.0,1.0,Coventry City,1.5,1.8,2023,Leicester City,Leicester City,-0.3,1.0,3.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.9,-1.55,-0.78,1.24,2.02,0.74,2.82,34.0,-12.9,-17.00,18.0,13.0,0.99,2.42,-1.165
7385,2023-08-12,Championship,Matchweek 2,Away,W,1.0,0.0,Huddersfield,1.4,1.2,2023,Leicester City,Leicester City,0.2,1.0,3.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.9,-1.05,-0.78,0.24,1.02,0.64,2.22,34.0,-12.9,-17.00,18.0,13.0,0.44,1.62,-0.915
7386,2023-08-19,Championship,Matchweek 3,Home,W,2.0,1.0,Cardiff City,0.7,1.1,2023,Leicester City,Leicester City,-0.4,1.0,3.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.9,-1.65,-0.78,1.24,2.02,-0.06,2.12,34.0,-12.9,-17.00,18.0,13.0,0.59,2.07,-1.215
7387,2023-08-26,Championship,Matchweek 4,Away,W,2.0,1.0,Rotherham Utd,1.4,0.6,2023,Leicester City,Leicester City,0.8,1.0,3.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.9,-0.45,-0.78,1.24,2.02,0.64,1.62,34.0,-12.9,-17.00,18.0,13.0,0.94,1.82,-0.615
7388,2023-09-02,Championship,Matchweek 5,Home,L,0.0,1.0,Hull City,1.2,0.3,2023,Leicester City,Leicester City,0.9,-1.0,0.0,0.3,-1.25,-1.78,-0.76,1.02,-0.76,1.02,0.0,-0.35,-2.78,-0.76,2.02,0.44,1.32,34.0,-12.9,-17.00,18.0,13.0,-0.16,1.67,-1.565
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13043,2024-04-24,Premier League,Matchweek 29,Away,L,2.0,4.0,Manchester Utd,0.8,2.9,2023,Sheffield United,Sheffield Utd,-2.1,-2.0,0.0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,-2.10,-2.00,2.00,4.00,0.80,2.90,27.3,-29.9,-47.88,22.0,22.0,1.40,3.45,-2.050
13044,2024-04-27,Premier League,Matchweek 35,Away,L,1.0,5.0,Newcastle Utd,1.5,3.1,2023,Sheffield United,Sheffield Utd,-1.6,-4.0,0.0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,-1.60,-4.00,1.00,5.00,1.50,3.10,27.3,-29.9,-47.88,22.0,22.0,1.25,4.05,-2.800
13045,2024-05-04,Premier League,Matchweek 36,Home,L,1.0,3.0,Nott'ham Forest,2.2,1.5,2023,Sheffield United,Sheffield Utd,0.7,-2.0,0.0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.70,-2.00,1.00,3.00,2.20,1.50,27.3,-29.9,-47.88,22.0,22.0,1.60,2.25,-0.650
13046,2024-05-11,Premier League,Matchweek 37,Away,L,0.0,1.0,Everton,0.6,2.3,2023,Sheffield United,Sheffield Utd,-1.7,-1.0,0.0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,-1.70,-1.00,0.00,1.00,0.60,2.30,27.3,-29.9,-47.88,22.0,22.0,0.30,1.65,-1.350
13047,2024-05-19,Premier League,Matchweek 38,Home,L,0.0,3.0,Tottenham,1.0,3.1,2023,Sheffield United,Sheffield Utd,-2.1,-3.0,0.0,1.0,0.00,0.00,0.00,0.00,0.00,0.00,0.0,-2.10,-3.00,0.00,3.00,1.00,3.10,27.3,-29.9,-47.88,22.0,22.0,0.50,3.05,-2.550

In [33]:
df.to_excel(r"C:\Users\George\Documents\University\Masters\DISS\Datasets\Match Dataset with Weights and Previous Season Data (1).xlsx")